Importing the necessary modules

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
import io

Loading the dataset

In [2]:
uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded['user_timings final.csv']))
df

Saving user_timings final.csv to user_timings final.csv


subject  sessionIndex  rep  H.period  DD.period.t  UD.period.t       H.t  \
0     kartik             1    1  0.097740     0.241737     0.143997  0.104170   
1     kartik             1    2  0.102349     0.230486     0.128137  0.097084   
2     kartik             1    3  0.101795     0.956869     0.855073  0.087984   
3     kartik             1    4  0.107638     0.500304     0.392665  0.081788   
4     kartik             1    5  0.094466     0.230914     0.136448  0.102051   
...      ...           ...  ...       ...          ...          ...       ...   
1033   Harsh             4   21  0.081503     0.154408     0.072906  0.089649   
1034   Harsh             4   22  0.084214     0.158789     0.074575  0.072914   
1035   Harsh             4   23  0.096142     0.181271     0.085129  0.095055   
1036   Harsh             4   24  0.079335     0.125875     0.046540  0.086316   
1037   Harsh             4   25  0.080061     0.089669     0.009608  0.095863   

        DD.t.i    UD.t.i       H.i  ...       H.a    DD.a.n    UD.a.n  \
0     0.183440  0.079270  0.102400  ...  0.089969  0.082232 -0.007738   
1     0.133811  0.036727  0.108120  ...  0.086330  0.070314 -0.016016   
2     0.121599  0.033615  0.108201  ...  0.092164  0.110766  0.018603   
3     0.113005  0.031217  0.093403  ...  0.096123  0.110807  0.014684   
4     0.121424  0.019373  0.103837  ...  0.097078  0.089562 -0.007516   
...        ...       ...       ...  ...       ...       ...       ...   
1033  0.088434 -0.001215  0.085204  ...  0.117907  0.140819  0.022912   
1034  0.123583  0.050668  0.095805  ...  0.132134  0.096262 -0.035873   
1035  0.144029  0.048974  0.081703  ...  0.123953  0.104879 -0.019074   
1036  0.133873  0.047556  0.057497  ...  0.139600  0.092088 -0.047512   
1037  1.576751  1.480888  0.089396  ...  0.154250  0.100869 -0.053381   

           H.n    DD.n.l    UD.n.l       H.l  DD.l.Return  UD.l.Return  \
0     0.089618  0.135616  0.045998  0.092679     0.200897     0.108218   
1     0.095217  0.146013  0.050796  0.089094     0.280403     0.191310   
2     0.091856  0.192280  0.100424  0.092151     0.262475     0.170324   
3     0.076902  0.165279  0.088376  0.094764     0.229971     0.135207   
4     0.107291  0.158869  0.051579  0.106750     0.363045     0.256295   
...        ...       ...       ...       ...          ...          ...   
1033  0.115329  1.195435  1.080107  0.090116     0.140167     0.050052   
1034  0.099090  0.021818 -0.077272  0.168661     0.569787     0.401126   
1035  0.106347  0.058932 -0.047415 -3.022046     0.126210    -0.023683   
1036  0.135591  0.073032 -0.062559 -2.726672     0.107108    -0.041189   
1037  0.100235  0.056937 -0.043298 -3.923082     0.105926    -0.026736   

      H.Return  
0     0.102322  
1     0.110564  
2     0.111403  
3     0.097279  
4     0.111081  
...        ...  
1033  0.100148  
1034  0.134795  
1035  0.077965  
1036  0.098201  
1037  0.097116  

[1038 rows x 34 columns]

Checking for any redundant values in the dataset

In [19]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1033    False
1034    False
1035    False
1036    False
1037    False
Length: 1038, dtype: bool

Dividing the data into features and labels

In [20]:
X = df.drop(['subject', 'sessionIndex', 'rep'], axis=1)
y = df['subject']

In [21]:
X

H.period  DD.period.t  UD.period.t       H.t    DD.t.i    UD.t.i  \
0     0.097740     0.241737     0.143997  0.104170  0.183440  0.079270   
1     0.102349     0.230486     0.128137  0.097084  0.133811  0.036727   
2     0.101795     0.956869     0.855073  0.087984  0.121599  0.033615   
3     0.107638     0.500304     0.392665  0.081788  0.113005  0.031217   
4     0.094466     0.230914     0.136448  0.102051  0.121424  0.019373   
...        ...          ...          ...       ...       ...       ...   
1033  0.081503     0.154408     0.072906  0.089649  0.088434 -0.001215   
1034  0.084214     0.158789     0.074575  0.072914  0.123583  0.050668   
1035  0.096142     0.181271     0.085129  0.095055  0.144029  0.048974   
1036  0.079335     0.125875     0.046540  0.086316  0.133873  0.047556   
1037  0.080061     0.089669     0.009608  0.095863  1.576751  1.480888   

           H.i    DD.i.e    UD.i.e       H.e  ...       H.a    DD.a.n  \
0     0.102400  0.281290  0.178890  0.092889  ...  0.089969  0.082232   
1     0.108120  0.140716  0.032596  0.091187  ...  0.086330  0.070314   
2     0.108201  0.637616  0.529415  0.101861  ...  0.092164  0.110766   
3     0.093403  0.152958  0.059555  0.092716  ...  0.096123  0.110807   
4     0.103837  0.130858  0.027021  0.102091  ...  0.097078  0.089562   
...        ...       ...       ...       ...  ...       ...       ...   
1033  0.085204  0.500397  0.415192  0.108266  ...  0.117907  0.140819   
1034  0.095805  0.071525 -0.024280  0.105453  ...  0.132134  0.096262   
1035  0.081703  0.094318  0.012615  0.093239  ...  0.123953  0.104879   
1036  0.057497  0.323807  0.266309  0.115429  ...  0.139600  0.092088   
1037  0.089396  0.090575  0.001180  0.081225  ...  0.154250  0.100869   

        UD.a.n       H.n    DD.n.l    UD.n.l       H.l  DD.l.Return  \
0    -0.007738  0.089618  0.135616  0.045998  0.092679     0.200897   
1    -0.016016  0.095217  0.146013  0.050796  0.089094     0.280403   
2     0.018603  0.091856  0.192280  0.100424  0.092151     0.262475   
3     0.014684  0.076902  0.165279  0.088376  0.094764     0.229971   
4    -0.007516  0.107291  0.158869  0.051579  0.106750     0.363045   
...        ...       ...       ...       ...       ...          ...   
1033  0.022912  0.115329  1.195435  1.080107  0.090116     0.140167   
1034 -0.035873  0.099090  0.021818 -0.077272  0.168661     0.569787   
1035 -0.019074  0.106347  0.058932 -0.047415 -3.022046     0.126210   
1036 -0.047512  0.135591  0.073032 -0.062559 -2.726672     0.107108   
1037 -0.053381  0.100235  0.056937 -0.043298 -3.923082     0.105926   

      UD.l.Return  H.Return  
0        0.108218  0.102322  
1        0.191310  0.110564  
2        0.170324  0.111403  
3        0.135207  0.097279  
4        0.256295  0.111081  
...           ...       ...  
1033     0.050052  0.100148  
1034     0.401126  0.134795  
1035    -0.023683  0.077965  
1036    -0.041189  0.098201  
1037    -0.026736  0.097116  

[1038 rows x 31 columns]

In [22]:
y

0       kartik
1       kartik
2       kartik
3       kartik
4       kartik
         ...  
1033     Harsh
1034     Harsh
1035     Harsh
1036     Harsh
1037     Harsh
Name: subject, Length: 1038, dtype: object

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from keras.models import Sequential
from keras.layers import Dense

In [24]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

In [25]:
y_encoded

array([1, 1, 1, ..., 0, 0, 0])

Dividing the data into training and testing part

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.4, random_state=42)

Standardize features using StandardScaler

In [27]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Building a simple neural network model with keras

In [28]:
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(len(label_encoder.classes_), activation='softmax'))

Compiling the model

In [29]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Training the model

In [30]:
model.fit(X_train_scaled, y_train, epochs=10, batch_size=32)

Epoch 1/10
20/20 [==============================] - 1s 2ms/step - loss: 0.6252 - accuracy: 0.7572
Epoch 2/10
20/20 [==============================] - 0s 2ms/step - loss: 0.3299 - accuracy: 0.9421
Epoch 3/10
20/20 [==============================] - 0s 2ms/step - loss: 0.1754 - accuracy: 0.9727
Epoch 4/10
20/20 [==============================] - 0s 2ms/step - loss: 0.0977 - accuracy: 0.9807
Epoch 5/10
20/20 [==============================] - 0s 2ms/step - loss: 0.0618 - accuracy: 0.9887
Epoch 6/10
20/20 [==============================] - 0s 2ms/step - loss: 0.0439 - accuracy: 0.9904
Epoch 7/10
20/20 [==============================] - 0s 3ms/step - loss: 0.0328 - accuracy: 0.9904
Epoch 8/10
20/20 [==============================] - 0s 2ms/step - loss: 0.0259 - accuracy: 0.9952
Epoch 9/10
20/20 [==============================] - 0s 2ms/step - loss: 0.0206 - accuracy: 0.9968
Epoch 10/10
20/20 [==============================] - 0s 2ms/step - loss: 0.0173 - accuracy: 0.9984


Evaluate the model on the test set

In [31]:
accuracy = model.evaluate(X_test_scaled, y_test)[1]
print(f'Model Accuracy: {accuracy}')

13/13 [==============================] - 0s 3ms/step - loss: 0.0298 - accuracy: 0.9904
Model Accuracy: 0.9903846383094788


In [32]:
X_test_scaled

array([[ 0.88500367, -0.4195527 , -0.46357582, ...,  0.49748028,
         0.4620129 , -0.61502761],
       [-0.71630288, -0.12695572, -0.09130755, ..., -0.45776359,
        -0.45856651,  0.99421719],
       [-0.64179058,  0.74311083,  0.77501988, ...,  0.50648802,
         0.48196159,  0.66590811],
       ...,
       [ 0.32818526, -0.40779993, -0.4241159 , ..., -0.31527266,
        -0.27693605, -1.04141855],
       [-0.2698472 , -0.31114836, -0.29770941, ..., -0.11185097,
        -0.12943418, -0.8485247 ],
       [ 2.30992924, -0.00251323, -0.11745641, ..., -0.46045883,
        -0.35423723, -0.94330826]])

In [33]:
model.predict(np.array([0.07678580284118652,0.16349077224731445,0.08670496940612793,0.07696676254272461,0.09451866149902344,0.017551898956298828,0.1054847240447998,0.09288573265075684,-0.012598991394042969,0.10107111930847168,0.2071990966796875,0.10612797737121582,0.06950139999389648,0.3039827346801758,0.2344813346862793,0.08726286888122559,0.11987924575805664,0.032616376876831055,0.1024618148803711,0.10581135749816895,0.0033495426177978516,0.08954787254333496,0.09755921363830566,0.008011341094970703,0.14449286460876465,0.10613298416137695,-0.038359880447387695,0.09683728218078613,0.34290289878845215,0.24606561660766602,0.08042645454406738],ndmin=2))

1/1 [==============================] - 0s 56ms/step


array([[0.70913035, 0.29086962]], dtype=float32)

In [35]:
# Input data for prediction
new_data = np.array([0.07678580284118652,0.16349077224731445,0.08670496940612793,0.07696676254272461,0.09451866149902344,0.017551898956298828,0.1054847240447998,0.09288573265075684,-0.012598991394042969,0.10107111930847168,0.2071990966796875,0.10612797737121582,0.06950139999389648,0.3039827346801758,0.2344813346862793,0.08726286888122559,0.11987924575805664,0.032616376876831055,0.1024618148803711,0.10581135749816895,0.0033495426177978516,0.08954787254333496,0.09755921363830566,0.008011341094970703,0.14449286460876465,0.10613298416137695,-0.038359880447387695,0.09683728218078613,0.34290289878845215,0.24606561660766602,0.08042645454406738])

# Reshape the input data to match the model's input shape
new_data = new_data.reshape(1, -1)

# Standardize the input data using the previously fitted scaler
new_data_scaled = scaler.transform(new_data)

# Make a prediction using the trained model
prediction = model.predict(new_data_scaled)

# Convert the predicted class to the original label using the label encoder
predicted_label = label_encoder.classes_[np.argmax(prediction)]

# Print the result
print(predicted_label)




1/1 [==============================] - 0s 37ms/step
Harsh


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
